config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user  
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must logged in to perform this action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new()
    @article = Article.new
  end
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def create()
    #render plain: params[:article].inspect
    @article = Article.create(article_param)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article created sucessfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @article.update(article_param)
      flash[:success] = "Articel updated successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was deleted successfully"
    redirect_to articles_path    
  end


  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_param
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "These was something wrong with your login information"
      render 'new'
    end  
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "welcome to the Aplha-blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)    
    end

    def require_same_user
      if current_user != @user
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    render 'home'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      size = options[:size]
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>
    
      <div class="article-body">
        <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
              <small>Created by: <%= article.user.username if article.user%>,
                <%= time_ago_in_words(article.created_at) %> ago,
                  last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
      </div>
      <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
            data: { confirm: "Are you sure you want to delete the article?"},
              class: "btn btn-xs btn-danger" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<div class="row">
<div class="col-xs-12"> 
  <%= render 'shared/errors', obj: @article %>
<%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>
   <div class="form-group row">
  <%= f.label :title, class: "col-sm-3 col-form-label" %>
   <div class="col-sm-10">
  <%= f.text_field :title, class: "form-control" %> 
   </div>
     </div>
  
 
 <div class="form-group row">
    <%= f.label :description, class: "col-sm-3 col-form-label"  %>
     <div class="col-sm-10">
    <%= f.text_area :description, class: "form-control" %>
    </div>
     </div>
  <div class="form-group ">
  <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>
<%= link_to "Article Listing", articles_path %>
 
 <%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing of aticles</h1>
<%= link_to "Create new Article", new_article_path %>
   <div align="center">
   <%= will_paginate @articles %>
   </div>
 <table class="table table-striped">

  <tr>
     <th>Title    </th>
     <th>Description</th>
     <th>Created By</th>
     <th>Created/Updated</th>
     <th>Action</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
     <td><%= article.description %></td>
     <td>
         <%= article.user.username if article.user %>
     </td>
      <td>
      Created at :<%= time_ago_in_words(article.created_at) %>
      Updated at :<%= time_ago_in_words(article.updated_at) %>
      </td>
     <td><%= link_to "Edit", edit_article_path(article) %>
     <%= link_to "Show", article_path(article) %>
      <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure want to delete this item"} %>
     </td>
  </tr>
  <% end %>
</table>
<div align="center">
   <%= will_paginate @articles %>
   </div>

app/views/articles/new.html.erb
<h1>Create new article</h1>

  <%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

<% if @article.user %>

<ul class="listing">

<div class="row center">

<div class="col-md-4 col-md-offset-4">

<li>Created by:</li>

<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>

<li class="article-title">

<%= link_to @article.user.username, user_path(@article.user) %>

</li>

<li><small>

<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>

</small></li>

</div>

</div>

</ul>

<% end %>

<h4 class="center description"><strong>Description:</strong></h4>

<hr>

<%= simple_format(@article.description) %>

<div class="article-actions">

<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(@article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

</div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

Copyright © <a href="enter in a link here">The Complete Ruby on Rails Developer</a>

by <a href="enter in a link here">Pankaj</a>

</small>

<nav>

<ul>

<li><%= link_to "Home", root_path %></li>

</ul>

</nav>

</footer>

</div>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
 <div class='alert alert-<%="#{name}"%>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg , :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%# <a class="navbar-brand" href="#">Alpha-Blog</a> %>
  <%= link_to "Alpha-Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Articles", articles_path, class: "nav-link"  %></li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <%= link_to "New Article", new_article_path, class: "dropdown-item"  %>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
    </ul>
    <ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

      <li><%= link_to 'Log out', logout_path, method: :delete %></li>

      <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
       <ul class="dropdown-menu">
        <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
        <li><%= link_to "View your profile", user_path(current_user) %></li>
        <li><a href="#">Something else here</a></li>  
        <li role="separator" class="divider"></li>
        <li><a href="#">Separated link</a></li>
      </ul>
  </li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', signup_path %></li>

<% end %>

</ul>
    <%# <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
  
   <%= render 'layouts/navigation' %>
   <%= render 'layouts/messages' %>
  <div class="container content">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<div class="panel panel-danger">
    
    
 <% if obj.errors.any? %>
  <div class="panel-heading">
    <h5><%= pluralize(obj.errors.count, "error")%></h5>
    </div>
   <div class="panel-body">
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>  
 </div>
  <%end%>
</div>

app/views/users/_form.html.erb
 <%= render 'shared/errors', obj: @user %>
<%= form_for(@user, :html => { class: "form-horizontal", role: "form" }) do |f| %>
   <div class="form-group row">
  <%= f.label :username, class: "col-sm-3 col-form-label" %>
   <div class="col-sm-10">
  <%= f.text_field :username, class: "form-control" %> 
   </div>
     </div>
  
 
 <div class="form-group row">
    <%= f.label :email, class: "col-sm-3 col-form-label"  %>
     <div class="col-sm-10">
    <%= f.email_field :email, class: "form-control" %>
    </div>
     </div>
     <div class="form-group row">
    <%= f.label :password, class: "col-sm-3 col-form-label"  %>
     <div class="col-sm-10">
    <%= f.password_field :password, class: "form-control" %>
    </div>
     </div>
  <div class="form-group ">
  <%= f.submit "Sign up", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
<div class="col-xs-12"> 
<h4> Update your acount </h4>
  <%= render 'form'%>
</div>
</div>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
  <div align="center">
  <div align="center">
   <%= will_paginate @articles %>
   </div>
    <% @users.each do |user| %>
      <ul class="listing">
        <div class="row">
          <div class="well col-md-4 col-md-offset-4">
            <li><%= link_to gravatar_for(user), user_path(user) %></li>
            <li class="article-title">
              <%= link_to user.username, user_path(user) %>
            </li>
            <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
          </div>
        </div>
      </ul>
    <% end %>
    <div align="center">
   <%= will_paginate @articles %>
   </div>
  </div>

app/views/users/new.html.erb
<div class="row">
<div class="col-xs-12"> 
<h4> Signup for Alpha blog </h4>
 <%= render 'form'%>
</div>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @user, size: 150 %>
    </div>
  </div>
  <h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">

<%= will_paginate @user_articles %>

</div>
<%= render 'articles/article', obj:  @user_articles %>
<div class="center">

<%= will_paginate @user_articles %>

</div>

app/views/welcome/home.html.erb
<h1>This is home page</h1> 